

MAIN_SYMBOLS = ['BTC/USDT', 'ETH/USDT', 'BCH/USDT', 'ETC/USDT', 'ADA/USDT','XRP/USDT', 'DOT/USDT', 'EOS/USDT', 'LTC/USDT']
ALT_SYMBOLS = ['UNI/USDT', 'XMR/USDT', 'ATOM/USDT', 'COMP/USDT', 'SOL/USDT', 'ALGO/USDT', 'FIL/USDT', 'XLM/USDT', 'AAVE/USDT']
PERIODS = ['30m', '1h', '4h']
ERROR_RATE = 0.05


PROCESS_COUNT=4

PREDICT=False

# HTTP_PROXY = 'http://127.0.0.1:1087'
HTTP_PROXY = None
NOTIFY_URL = 'https://sc.ftqq.com/[****]'

